export const LOAD_USER_LOGIN = "LOAD_USER_LOGIN";
export const SUCCESS_USER_LOGIN = "SUCCESS_USER_LOGIN";
export const ERROR_USER_LOGIN = "ERROR_USER_LOGIN";

export const LOAD_USER_SIGNOUT = "LOAD_USER_SIGNOUT";
export const SUCCESS_USER_SIGNOUT = "SUCCESS_USER_SIGNOUT";
export const ERROR_USER_SIGNOUT = "ERROR_USER_SIGNOUT";
